Documents service
OwlByTech/optitech-api pull request #24
Opened 2024-07-03 20:11 UTC by JosephSC0121

## Description

Se siguio la estructura planteada anteriormente.
 
Servicio format
-get by id
![image](https://github.com/OwlByTech/optitech-api/assets/119358195/c47f00db-4538-47e7-8362-04266914a0be)

## How Has This Been Tested?

postman

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-04 15:53 UTC, Alejandro-Suarez-Rincon approved these changes
Usar Hoppscothc para que todos tengamos acceso a las peticiones.

2024-07-06 14:19 UTC, CamiloArias12 commented on database/schemas/20240526020158_document.up.sql
Deberia tener un nombre para mostrarlo asi
![image](https://github.com/OwlByTech/optitech-api/assets/127451734/30d2a43b-cc6e-45f2-baad-22fbd843b3d6)

2024-07-08 19:13 UTC, JosephSC0121 commented on database/schemas/20240526020158_document.up.sql
no entendi

2024-07-09 16:32 UTC, Camilo-Camargo requested changes

2024-07-09 16:32 UTC, Camilo-Camargo commented on internal/config/config.go
> +var DigitalOcean *DigitalOceanStruct
me parece mejor dejarlo en Env.

2024-07-09 16:32 UTC, Camilo-Camargo commented on internal/repository/documents.go
> +		Status:      string(repoRes.Status),
porque string()

2024-07-09 16:32 UTC, Camilo-Camargo commented on internal/service/documents/documents.go
> +	//TODO: Change this for multipart
@CamiloArias12

2024-07-09 19:11 UTC, JosephSC0121 commented on internal/repository/documents.go
> +		Status:      string(repoRes.Status),
pq como es un ENUM sqlc lo sqlc lo toma como tipo STATUS, entonces para obtener el valor string se hace el cast
![image](https://github.com/OwlByTech/optitech-api/assets/119358195/9c1c1b1f-938f-4d70-a79a-e567a2bbb848)

2024-07-09 19:21 UTC, JosephSC0121 commented on internal/config/config.go
> +var DigitalOcean *DigitalOceanStruct
[f365b5a](https://github.com/OwlByTech/optitech-api/pull/24/commits/f365b5a8801008faa32b675b535b2e1e7b95b61c)****

2024-07-12 21:51 UTC, CamiloArias12 commented on database/schemas/20240526020158_document.up.sql
![image](https://github.com/user-attachments/assets/feb9eed3-4148-44dc-a03b-9093ade32432)
agregar el campo name para mostrarlo

2024-07-12 21:59 UTC, Camilo-Camargo commented on internal/dto/document/create.go
> +type CreateDocumentReq struct {
Falta agregar nombre de documento

2024-07-12 21:59 UTC, Camilo-Camargo commented on internal/service/documents/documents.go
> +
```suggestion
```

2024-07-12 22:54 UTC, Camilo-Camargo approved these changes

2024-07-12 22:55 UTC, merged