service mailing
OwlByTech/optitech-api pull request #3
Opened 2024-06-03 23:55 UTC by Alejandro-Suarez-Rincon

# Service Mailing

## Description

![Captura desde 2024-06-03 18-01-16](https://github.com/OwlByTech/optitech-api/assets/126360945/49de6a09-600a-4843-b78e-b453ab8cc347)

Este pr tiene el servicio de envio de correo masivo en especial para el envio de correo y contraseña temporal del usuario.

### Summary
Se siguió el flujo discutido en reunión

### Documentation
gomail: https://pkg.go.dev/gopkg.in/gomail.v2#section-readme
smtp/golang: https://pkg.go.dev/net/smtp
mjml: https://documentation.mjml.io/
sendMailGolang: https://mailtrap.io/blog/golang-send-email/

## How Has This Been Tested?
Por medio de postman.
![imagen](https://github.com/OwlByTech/optitech-api/assets/126360945/2f840d3f-2593-4464-8881-9227054361c3)

## Checklist:
- [x]  My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-04 00:01 UTC, CamiloArias12 requested changes

2024-06-04 00:03 UTC, JosephSC0121 commented on internal/service/mailing/mailing.go
> +	// Deleite temporal
```suggestion
	// Delete temporal
```

2024-06-04 00:04 UTC, JosephSC0121 commented on internal/service/mailing/mailing.go
> +	d := gomail.NewDialer(os.Getenv("EMAIL_SMTP_HOST"), port, os.Getenv("EMAIL_FROM"), os.Getenv("EMAIL_SMTP_PASSWORD"))
Qué opina alejo de generar la contraseña? en vez de leerla en el .env, para que no sea la misma todo el rato

2024-06-04 00:06 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +	d := gomail.NewDialer(os.Getenv("EMAIL_SMTP_HOST"), port, os.Getenv("EMAIL_FROM"), os.Getenv("EMAIL_SMTP_PASSWORD"))
Esa contraseña es la contraseña del no-reply de nosotros, la contraseña que se le manda al usuario va en el JSON

2024-06-04 00:06 UTC, JosephSC0121 commented on internal/service/mailing/mailing.go
> +	d := gomail.NewDialer(os.Getenv("EMAIL_SMTP_HOST"), port, os.Getenv("EMAIL_FROM"), os.Getenv("EMAIL_SMTP_PASSWORD"))
otra cosa, se puede llamar lo que se necesita del .env en otro archivo, por ejemplo https://github.com/OwlByTech/optitech-api/blob/feature/create_dtos/database/db.go, para no dejarlo directamente en el servicio

2024-06-04 00:08 UTC, JosephSC0121 commented on internal/service/mailing/mailing.go
> +	d := gomail.NewDialer(os.Getenv("EMAIL_SMTP_HOST"), port, os.Getenv("EMAIL_FROM"), os.Getenv("EMAIL_SMTP_PASSWORD"))
ahhhh okey

2024-06-04 00:44 UTC, Camilo-Camargo commented on internal/dto/mailing/send.go
> +	Emails          []string `json:"emails" validate:"required,min=1,dive,email"`
por qué necesitaríamos que el password envíe a muchos correos la misma información?

2024-06-04 00:44 UTC, Camilo-Camargo commented on internal/dto/mailing/send.go
> +	PasswordMessage string   `json:"passwordMessage" binding:"required"`
Creo que sobraría message, ya sabemos que las variables serán utilizadas para el mensaje.
```suggestion
	Password string   `json:"password" binding:"required"`
```

2024-06-04 00:44 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +	}
```suggestion
```

2024-06-04 00:44 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +func CreateMailingService(send dto.MailingReq) error {
```suggestion
func SendPassword(send dto.MailingReq) error {
```
Ya sabemos que es un servicio de mail, pero específicamente este que hace?, en este caso envía password.

2024-06-04 00:44 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +func ReadMJML(email string, password string) (string, error) {
Esta función podría ser más abstracta que permita leer y remplazar cualquier tipo de dato, en este caso sería encerrar email, y password, en una struct, de hecho para hacerlo genérico se puede con interface{} y se podría utilizar json para abordar esto, como los dto de handler.

2024-06-04 00:44 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +func ReadMJML(email string, password string) (string, error) {
https://github.com/OwlByTech/optitech-api/blob/872c32255ce5b2ba70629f52b1f162206d3889c7/internal/handler/client.go#L12 y https://github.com/OwlByTech/optitech-api/blob/872c32255ce5b2ba70629f52b1f162206d3889c7/internal/handler/client.go#L39

2024-06-04 00:44 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +	cmd := exec.Command("mjml", tempMJMLFile, "-o", "temp.html")
Este comando está genial, pero será mejor  en cli, como las migrations y seeders, porque en cada consulta se crea y por eso se demora cada petición.

2024-06-04 00:44 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +	}
no es necesario removerlos si se crean mediante el cli, ya que estos archivos si se vuelven a generar serán los mismos.

2024-06-04 00:44 UTC, Camilo-Camargo commented on internal/service/mailing/template.mjml
este, template es solo para un caso, se pueden guardar en una carpeta separando los servicios, ejemplo `templates/password.mjml`

2024-06-05 03:36 UTC, Alejandro-Suarez-Rincon commented on internal/dto/mailing/send.go
> +	Emails          []string `json:"emails" validate:"required,min=1,dive,email"`
osea solo dejarlo para un solo correo?

2024-06-05 03:45 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
Ingles: https://github.com/OwlByTech/optitech-api/pull/3/commits/8f279e7ce2b4af6dbada59de0c05143176aa1ff1

2024-06-05 03:45 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +	// Deleite temporal
Solucionado: https://github.com/OwlByTech/optitech-api/pull/3/commits/8f279e7ce2b4af6dbada59de0c05143176aa1ff1

2024-06-05 03:56 UTC, Alejandro-Suarez-Rincon commented on go.mod
> +	github.com/joho/godotenv v1.5.1 // indirect
https://github.com/OwlByTech/optitech-api/pull/3/commits/767812d259daac2ea037403f19e2c75ebe507fca

2024-06-05 03:56 UTC, Alejandro-Suarez-Rincon commented on internal/dto/mailing/send.go
> +type MailingReq struct {
Cambiado: https://github.com/OwlByTech/optitech-api/pull/3/commits/8f279e7ce2b4af6dbada59de0c05143176aa1ff1

2024-06-05 03:57 UTC, Alejandro-Suarez-Rincon commented on internal/dto/mailing/send.go
> +	PasswordMessage string   `json:"passwordMessage" binding:"required"`
cambiado: https://github.com/OwlByTech/optitech-api/pull/3/commits/8f279e7ce2b4af6dbada59de0c05143176aa1ff1

2024-06-05 03:57 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +	}
Eliminado: https://github.com/OwlByTech/optitech-api/pull/3/commits/8f279e7ce2b4af6dbada59de0c05143176aa1ff1

2024-06-05 03:57 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +func CreateMailingService(send dto.MailingReq) error {
Cambiado: https://github.com/OwlByTech/optitech-api/pull/3/commits/8f279e7ce2b4af6dbada59de0c05143176aa1ff1

2024-06-05 03:58 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +	}
Elimine esa parte, falta el cli

https://github.com/OwlByTech/optitech-api/pull/3/commits/8f279e7ce2b4af6dbada59de0c05143176aa1ff1

2024-06-06 11:56 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +	}
Yo creo que agregarlo en este pr

2024-06-07 02:44 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +func ReadMJML(email string, password string) (string, error) {
Cambiada a mas abstracta: https://github.com/OwlByTech/optitech-api/pull/3/commits/7826ebd9dfab5f6c015ad9b17bcf4b311bb6c758

2024-06-07 02:46 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/template.mjml
cambio orden de carpetas de `template` dentro del servicio de `mailing`:
`service/mailing/templates/templatePassword.mjml`
https://github.com/OwlByTech/optitech-api/pull/3/commits/7826ebd9dfab5f6c015ad9b17bcf4b311bb6c758

2024-06-07 02:52 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +	}
Ya lo coloque otra ves: https://github.com/OwlByTech/optitech-api/pull/3/commits/7826ebd9dfab5f6c015ad9b17bcf4b311bb6c758

2024-06-07 09:18 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +	}
el cli alejo

2024-06-07 09:20 UTC, Camilo-Camargo commented on internal/service/mailing/template.mjml
el nombre del archivo `template-password.mjml` o `template_password.mjml`

2024-06-07 09:25 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +func ReadMJML(data interface{}) (string, error) {
Agregar como parámetro el nombre del template, así como la función se llama ReadMJML permite leer otros mjml, aunque podríamos llamarlo parseMJML.

2024-06-07 09:25 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +func ReadMJML(data interface{}) (string, error) {
ese data tambien podriamos validarlo, la misma idea de dto, https://github.com/OwlByTech/optitech-api/blob/872c32255ce5b2ba70629f52b1f162206d3889c7/internal/handler/client.go#L39, pero tendriamos que crear el dto con sus arguments de json https://github.com/OwlByTech/optitech-api/blob/872c32255ce5b2ba70629f52b1f162206d3889c7/internal/dto/client/create.go#L4

2024-06-07 15:11 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +func ReadMJML(data interface{}) (string, error) {
El data viene lo que trae el dto, osea el email, password y subject, para que sea abstracto.

Para que llegue el parámetro de que tipo de template quiere leer, eso seria meterlo en un dto?, que llegue en una petición, así como llega el email, password y subject?

2024-06-07 15:23 UTC, JosephSC0121 commented on internal/config/config.go
> +// Config holds the configuration for the email server
Son realmente necesarios estos comments? siento que se entiende que se está haciendo sin ellos

2024-06-07 16:21 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +func ReadMJML(data interface{}) (string, error) {
Entiendo, pero validar no significa que lleve el tipo de dato dentro de la función, sino solo escribir `dto.ValidateDTO(data) ` dentro de la función, y debe enviar el data como un dto que incorpore `json:...;

2024-06-07 19:47 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/template.mjml
https://github.com/OwlByTech/optitech-api/pull/3/commits/fc14e99549f52c9eb1acfced867986238d8d6cfc

2024-06-07 19:48 UTC, Alejandro-Suarez-Rincon commented on internal/config/config.go
> +// Config holds the configuration for the email server
Solo los coloque para una rápida interpretación, pero si no los consideran necesarios, los puedo retirar: https://github.com/OwlByTech/optitech-api/pull/3/commits/fc14e99549f52c9eb1acfced867986238d8d6cfc

2024-06-07 21:50 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +	}
cli: https://github.com/OwlByTech/optitech-api/pull/3/commits/63b019384aaf64decbb4ebaec999695805e59095

2024-06-07 21:51 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +	cmd := exec.Command("mjml", tempMJMLFile, "-o", "temp.html")
cli: https://github.com/OwlByTech/optitech-api/pull/3/commits/63b019384aaf64decbb4ebaec999695805e59095

2024-06-08 04:09 UTC, Camilo-Camargo commented on go.mod
> +	gopkg.in/alexcesaro/quotedprintable.v3 v3.0.0-20150716171945-2caba252f4dc // indirect
esta libreria para que nos ayuda?

2024-06-08 04:09 UTC, Camilo-Camargo commented on internal/service/mailing/convert.go
> +func ConvertMJML(mjmlFile string) error {
Me gusta lo que hizo de separar la función y utilizarla en CLI, Genial @Alejandro-Suarez-Rincon

2024-06-08 04:09 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +	mjmlContent, err := os.ReadFile("./internal/service/mailing/templates/template-password.mjml")
Podríamos agregar que la función reciba el nombre del template a leer, así la dejamos abstracta

2024-06-08 04:09 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +	mjmlContent, err := os.ReadFile("./internal/service/mailing/templates/template-password.mjml")
Veo que sigue cargando el mjml, ya no es necesario si en el cli se genera, es cargar el html generado.

2024-06-08 04:09 UTC, Camilo-Camargo commented on internal/service/mailing/mailing.go
> +		return "", fmt.Errorf("error removing temporary HTML file: %w", err)
Todo esto se elimina si leemos solo el html generado y cargamos en memoria el archivo editamos las variables y luego cuando se retorne se eliminara por el garbage collector

2024-06-09 01:35 UTC, Alejandro-Suarez-Rincon commented on go.mod
> +	gopkg.in/alexcesaro/quotedprintable.v3 v3.0.0-20150716171945-2caba252f4dc // indirect
uy yo no la instale, a menos que se aya metido cuando hice el cli, pero no metí librerías, ya lo reviso

2024-06-11 02:00 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +		return "", fmt.Errorf("error removing temporary HTML file: %w", err)
Creo que se soluciona asi:[68e0b41](https://github.com/OwlByTech/optitech-api/pull/3/commits/68e0b41c1e644124aa969663c555ab09761355de)

2024-06-11 02:00 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +	mjmlContent, err := os.ReadFile("./internal/service/mailing/templates/template-password.mjml")
[68e0b41](https://github.com/OwlByTech/optitech-api/pull/3/commits/68e0b41c1e644124aa969663c555ab09761355de)

2024-06-12 01:07 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +		return "", fmt.Errorf("error removing temporary HTML file: %w", err)
https://github.com/OwlByTech/optitech-api/pull/3/commits/40cc54569cd5dd2be7310c221f93bf2e9e1eba93

2024-06-12 01:07 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +	mjmlContent, err := os.ReadFile("./internal/service/mailing/templates/template-password.mjml")
https://github.com/OwlByTech/optitech-api/pull/3/commits/40cc54569cd5dd2be7310c221f93bf2e9e1eba93

2024-06-12 01:07 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +	mjmlContent, err := os.ReadFile("./internal/service/mailing/templates/template-password.mjml")
https://github.com/OwlByTech/optitech-api/pull/3/commits/40cc54569cd5dd2be7310c221f93bf2e9e1eba93

2024-06-12 01:08 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/convert.go
> +func ConvertMJML(mjmlFile string) error {
https://github.com/OwlByTech/optitech-api/pull/3/commits/40cc54569cd5dd2be7310c221f93bf2e9e1eba93

2024-06-12 01:08 UTC, Alejandro-Suarez-Rincon commented on go.mod
> +	gopkg.in/alexcesaro/quotedprintable.v3 v3.0.0-20150716171945-2caba252f4dc // indirect
https://github.com/OwlByTech/optitech-api/pull/3/commits/40cc54569cd5dd2be7310c221f93bf2e9e1eba93

2024-06-12 01:08 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +func ReadMJML(data interface{}) (string, error) {
https://github.com/OwlByTech/optitech-api/pull/3/commits/40cc54569cd5dd2be7310c221f93bf2e9e1eba93

2024-06-12 01:08 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +func ReadMJML(data interface{}) (string, error) {
https://github.com/OwlByTech/optitech-api/pull/3/commits/40cc54569cd5dd2be7310c221f93bf2e9e1eba93

2024-06-12 01:08 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +	}
https://github.com/OwlByTech/optitech-api/pull/3/commits/40cc54569cd5dd2be7310c221f93bf2e9e1eba93

2024-06-12 01:08 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +	cmd := exec.Command("mjml", tempMJMLFile, "-o", "temp.html")
https://github.com/OwlByTech/optitech-api/pull/3/commits/40cc54569cd5dd2be7310c221f93bf2e9e1eba93

2024-06-12 01:09 UTC, Alejandro-Suarez-Rincon commented on internal/service/mailing/mailing.go
> +func ReadMJML(email string, password string) (string, error) {
https://github.com/OwlByTech/optitech-api/pull/3/commits/40cc54569cd5dd2be7310c221f93bf2e9e1eba93

2024-06-12 01:17 UTC, JosephSC0121 approved these changes

2024-06-12 02:18 UTC, Camilo-Camargo commented on .gitignore
> +internal/services/mailing/templates/* .html
```suggestion
internal/services/mailing/templates/*.html
```

2024-06-12 02:41 UTC, Alejandro-Suarez-Rincon commented on .gitignore
> +internal/services/mailing/templates/* .html
cambiado: https://github.com/OwlByTech/optitech-api/pull/3/commits/b1f940001f389b5b10793b047c20e29b14e66ddd

2024-06-12 02:43 UTC, Camilo-Camargo approved these changes

2024-06-12 09:43 UTC, CamiloArias12 approved these changes

2024-06-12 14:27 UTC, merged