SEEDS
OwlByTech/optitech-api pull request #4
Opened 2024-06-07 00:11 UTC by JosephSC0121

# Creación de SEED inicial de las entidades del modelo

## Description
En este pull request se creará el seed de las entidades que las requieran

### Documentación que consulté 

https://docs.rocket.chat/use-rocket.chat/workspace-administration/permissions
https://docs.rocket.chat/setup-and-configure/roles-in-rocket.chat

## How Has This Been Tested?

Próximamente se agregarán test unitarios

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-07 03:29 UTC, Alejandro-Suarez-Rincon approved these changes

2024-06-07 09:27 UTC, Camilo-Camargo commented on database/json_data/json_reader.go
> +	err = json.Unmarshal(jsonFile, dto)
Podríamos validar el dto después del unmarshal, https://github.com/OwlByTech/optitech-api/blob/872c32255ce5b2ba70629f52b1f162206d3889c7/internal/handler/client.go#L39, pero tendriamos que crear el dto con sus arguments de json https://github.com/OwlByTech/optitech-api/blob/872c32255ce5b2ba70629f52b1f162206d3889c7/internal/dto/client/create.go#L4

2024-06-07 09:27 UTC, Camilo-Camargo commented on database/seeders/permission.go
> +	curTime := time.Now()
Qué opinan de definir la variable antes de usarla, para no almacenarlas antes?

2024-06-07 09:27 UTC, Camilo-Camargo commented on database/seeders/permission.go
> +		return fmt.Errorf("Error al leer el JSON: %v", err)
Errores en Ingles

2024-06-07 09:27 UTC, Camilo-Camargo commented on database/seeders/permission.go
> +	}
no estoy seguro si se puede llenar desde una lista con sqlc, podríamos verlo

2024-06-07 12:34 UTC, CamiloArias12 requested changes

2024-06-07 12:34 UTC, CamiloArias12 commented on database/json_data/permission.json
El permiso code deberia ir en mayuscula

2024-06-07 12:34 UTC, CamiloArias12 commented on internal/dto/asesor/create.go
> +}
```suggestion
type CreateAsesorReq struct {
	ClientId int64  `json:"client_id" validate:"required"`
	Username string `json:"username" validate:"required,username"`
	Photo    string `json:"photo" validate:"required"`
	About    string `json:"about" validate:"required"`
}
```

2024-06-07 16:20 UTC, JosephSC0121 commented on database/json_data/permission.json
por que?

2024-06-07 16:21 UTC, JosephSC0121 commented on database/seeders/permission.go
> +	}
![image](https://github.com/OwlByTech/optitech-api/assets/119358195/25f94a27-7d25-4ff0-a9b8-4299bdc14acf)
todo parece llenarse correctamente

2024-06-07 16:21 UTC, JosephSC0121 commented on database/seeders/permission.go
> +		return fmt.Errorf("Error al leer el JSON: %v", err)
[a6c4456](https://github.com/OwlByTech/optitech-api/pull/4/commits/a6c445615888f27cd7839448778dfb087f60868d)

2024-06-07 16:23 UTC, Camilo-Camargo commented on database/seeders/permission.go
> +	}
Se llena, pero uno por uno, sería investigar si se puede llenar  la lista completa como un batch.

2024-06-07 16:24 UTC, Camilo-Camargo commented
Falta realizar merge de develop

2024-06-07 16:28 UTC, JosephSC0121 commented on database/json_data/json_reader.go
> +	err = json.Unmarshal(jsonFile, dto)
no se podria usar el mismo dto?

2024-06-07 16:28 UTC, JosephSC0121 commented on database/seeders/permission.go
> +	}
okey

2024-06-10 14:20 UTC, CamiloArias12 approved these changes

2024-06-11 21:49 UTC, JosephSC0121 commented on database/seeders/permission.go
> +	curTime := time.Now()
es lo mismo

2024-06-12 11:09 UTC, Camilo-Camargo commented on database/json_data/json_reader.go
> +	err = json.Unmarshal(jsonFile, dto)
sip con el mismo dto, pero utilizando `dto.ValidateDTO(dto)`

2024-06-12 11:18 UTC, Camilo-Camargo commented on database/seeders/permission.go
> +	curTime := time.Now()
nop, si las definimos al comienzo y existe un error antes, las variables se almacenan y no cumplieron su objetivo de ser utilizadas, por lo cual se almacenan consumiendo memoria, mejor definirlas antes de utilizarlas.

2024-06-12 11:22 UTC, Camilo-Camargo commented on database/schemas/20240604021029_services.up.sql
> +    service_name VARCHAR(255) NOT NULL,
```suggestion
    name VARCHAR(255) NOT NULL,
```

2024-06-12 11:22 UTC, Camilo-Camargo commented on database/schemas/20240604211423_permission.up.sql
> +    permission_description VARCHAR(255) NOT NULL,
```suggestion
    name VARCHAR(50) NOT NULL,
    code VARCHAR(50) NOT NULL,
    description VARCHAR(255) NOT NULL,
```

2024-06-12 11:22 UTC, Camilo-Camargo commented on database/schemas/20240608013344_standars.up.sql
> +    standard VARCHAR(255) NOT NULL,
```suggestion
    name VARCHAR(255) NOT NULL,
```

2024-06-12 13:25 UTC, CamiloArias12 approved these changes

2024-06-12 22:14 UTC, JosephSC0121 commented on database/schemas/20240604021029_services.up.sql
> +    service_name VARCHAR(255) NOT NULL,
la cosa es que no solo cambia ahi camilo :)

2024-06-12 22:14 UTC, JosephSC0121 commented on database/schemas/20240604211423_permission.up.sql
> +    permission_description VARCHAR(255) NOT NULL,
la cosa es que no solo cambia ahi camilo :)

2024-06-12 22:14 UTC, JosephSC0121 commented on database/schemas/20240608013344_standars.up.sql
> +    standard VARCHAR(255) NOT NULL,
la cosa es que no solo cambia ahi camilo :)

2024-06-12 22:27 UTC, JosephSC0121 commented on database/schemas/20240608013344_standars.up.sql
> +    standard VARCHAR(255) NOT NULL,
https://github.com/OwlByTech/optitech-api/pull/4/commits/d733cf9f31ef7e0c716bee376d052876e044f892

2024-06-12 22:27 UTC, JosephSC0121 commented on database/schemas/20240604211423_permission.up.sql
> +    permission_description VARCHAR(255) NOT NULL,
https://github.com/OwlByTech/optitech-api/pull/4/commits/d733cf9f31ef7e0c716bee376d052876e044f892

2024-06-12 22:27 UTC, JosephSC0121 commented on database/schemas/20240604021029_services.up.sql
> +    service_name VARCHAR(255) NOT NULL,
https://github.com/OwlByTech/optitech-api/pull/4/commits/d733cf9f31ef7e0c716bee376d052876e044f892

2024-06-12 22:48 UTC, JosephSC0121 commented on database/json_data/json_reader.go
> +	err = json.Unmarshal(jsonFile, dto)
ahora mismo no puedo hacerlo pqor la forma como estoy implementando el seeder no puedo usar esa función, me tira error, me gustaría avanzar en funcionalidades y después refacttorizar
https://www.youtube.com/watch?v=bLHL75H_VEM

2024-06-12 22:49 UTC, JosephSC0121 commented on database/seeders/permission.go
> +	curTime := time.Now()
[fc55b39](https://github.com/OwlByTech/optitech-api/pull/4/commits/fc55b3900cc17331b45d834aa438ff2600a98794)

2024-06-13 01:02 UTC, Camilo-Camargo approved these changes

2024-06-13 16:42 UTC, Alejandro-Suarez-Rincon approved these changes

2024-06-14 01:15 UTC, merged